# Changes here will be overwritten by Copier
_commit: 7ccb63e
_src_path: gh:LabAutomationAndScreening/copier-aws-organization.git
account_email_domain: gmail.com
account_email_prefix: ejfine
aws_identity_center_id: d-9067c20053
aws_production_account_id: '789893201852'
central_infra_github_organization_name: ejfine
central_infra_repo_name: aws-central-infrastructure
description: Manage my AWS organization
pulumi_stack_name: prod
python_version: 3.12.7
repo_name: aws-organization
ssh_port_number: 51446
use_windows_in_ci: false

