# Changes here will be overwritten by Copier
_commit: 1eeffa6
_src_path: gh:LabAutomationAndScreening/copier-aws-organization.git
aws_identity_center_id: d-9067c20053
aws_production_account_id: '789893201852'
description: Manage my AWS organization
pulumi_stack_name: prod
python_version: 3.12.7
repo_name: aws-organization
ssh_port_number: 51446
use_windows_in_ci: false

