# ============== WARNING ==============================================================================
# File is managed by copier template: gh:LabAutomationAndScreening/copier-base-template.git
# See .config/.copier-managed-files.json for details.
#
# You are welcome to make changes to this file in your repo if they are custom to your project,
# but if the change should be shared with other projects, please backport it to the template repo.
# =====================================================================================================
[project]
name = "aws-organization"
version = "0.1.0"
description = "Managing the AWS Organization and Accounts"

readme = "README.md"
requires-python = ">=3.13.2"

dependencies = [
    # Specific to this template


    # Managed by upstream template
    "pyrefly>=1.3.2",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "pytest-randomly>=5.0.0",
    "pulumi>=3.265.0",
    "pulumi-aws>=7.48.0",
    "pulumi-aws-native>=1.81.0",
    "pulumi-command>=1.2.1",
    "ephemeral-pulumi-deploy>=0.0.8",
    "lab-auto-pulumi>=0.3.0",
    "boto3>=1.43.88",
    "boto3-stubs[all]>=1.43.88",
    "pydantic>=2.13.5",
    "typing-extensions>=4.16.0",
]

[tool.uv]
package = true
