# ============== WARNING ==============================================================================
# File is managed by copier template: gh:LabAutomationAndScreening/copier-aws-organization.git
# See .config/.copier-managed-files.json for details.
#
# You are welcome to make changes to this file in your repo if they are custom to your project,
# but if the change should be shared with other projects, please backport it to the template repo.
# =====================================================================================================
name: AWS ECR Auth
description: 'Use OIDC to Authenticate and login to an AWS ECR.'

inputs:
  aws-region:
    description: AWS region to use for ECR authentication
    required: false
    default: 'us-east-1'
  role-arn:
    description: AWS IAM Role ARN to assume for ECR authentication
    required: false
    default: 'arn:aws:iam::000000000000:role/CoreInfraBaseAccess'

runs:
  using: composite
  steps:
    - name: OIDC Auth for ECR
      uses: aws-actions/configure-aws-credentials@v6.3.0
      with:
        role-to-assume: ${{ inputs.role-arn }}
        aws-region: ${{ inputs.aws-region }}
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2.1.7
