version: '3.8'
services:
  devcontainer:
    build:
      context: .
      args:
        REPO_NAME: aws-organization
    # You can run `devcontainer-info content-url` in codespaces to see what image base is
    volumes:
      - ..:/workspaces/aws-organization:cached
      # Break out the venv folder as a separate docker volume for better performance on Windows hosts
      - python_venv:/workspaces/aws-organization/.venv
    command: sleep infinity
    ports:
      - "51446:2222"
    environment:
      - AWS_PROFILE=localstack


volumes:
  python_venv: {}
