name: Pulumi ephemeral deploy
description: Setup Pulumi and run the ephemeral deploy CLI
inputs:
  project-dir:
    type: string
    description: What's the relative path to the project (end in slash)?
    required: true
  stack-name:
    type: string
    description: What's the Pulumi Stack name?
    required: true
  cli-action:
    type: string
    description: What's the Pulumi Ephemeral CLI action?
    required: false
    default: ''
  aws-account-id:
    type: string
    description: What's the AWS Account ID for the role to assume?
    required: true
  aws-role-name:
    type: string
    description: What's the AWS role name?
    required: false
  aws-region:
    type: string
    description: What's the AWS region of the role?
    required: false
    default: us-east-1



runs:
  using: composite
  steps:
    - name: Install Pulumi
      run: sh .devcontainer/install-pulumi-cli.sh ${{ inputs.project-dir }}uv.lock
      shell: bash
