name: CI

on:
  push:
    branches-ignore:
      - 'gh-readonly-queue/**' # don't run (again) when on these special branches created during merge groups; the `on: merge_group` already triggers it.
  pull_request:
    branches-ignore:
      - 'gh-readonly-queue/**' # don't run (again) when on these special branches created during merge groups; the `on: merge_group` already triggers it.
  merge_group:

env:
  PYTHONUNBUFFERED: True
  PRE_COMMIT_HOME: ${{ github.workspace }}/.precommit_cache

permissions:
    id-token: write # needed to assume OIDC roles (e.g. for downloading from CodeArtifact)

jobs:
  get-values:
    uses: ./.github/workflows/get-values.yaml
    permissions:
      contents: write # needed for updating dependabot branches

  check-skip-duplicate:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: read # needed to check if PR exists for current branch
    outputs:
      should-run: ${{ steps.check.outputs.should-run }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.1
        with:
          persist-credentials: false
      - id: check
        uses: ./.github/actions/check-skip-duplicates

  lint:
    needs:
      - get-values
      - check-skip-duplicate
    if: needs.check-skip-duplicate.outputs.should-run == 'true'
    name: Pre-commit
    uses: ./.github/workflows/pre-commit.yaml
    permissions:
      contents: write # needed for mutex
      id-token: write # needed to assume OIDC roles (e.g. for downloading from CodeArtifact)
    with:
      python-version: 3.13.2

  pulumi-workflow:
    uses: ./.github/workflows/pulumi-aws.yml
    needs:
      - get-values
      - check-skip-duplicate
      - lint
    if: needs.check-skip-duplicate.outputs.should-run == 'true'
    permissions:
      id-token: write # needed to assume OIDC roles (e.g. for downloading from CodeArtifact)
      contents: write # needed for mutex
      pull-requests: write # needed to potentially post the preview on the PR as a comment
    with:
      AWS_REGION: us-east-1
      PULUMI_STACK_NAME: prod
      PYTHON_VERSION: 3.13.2
      DEPLOY_SCRIPT_MODULE_NAME: aws_organization.lib
      PULUMI_PREVIEW: true
      PREVIEW_ROLE_NAME: OrgRootInfraPreview
      PULUMI_UP: ${{ github.ref == 'refs/heads/main' }}
      PULUMI_UP_ROLE_NAME: OrgRootInfraDeploy
      AWS_ACCOUNT_ID: "789893201852"
      SHOW_PREVIEW_COMMENT_ON_PR: ${{ github.event_name == 'pull_request' }}

  workflow-summary:
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    needs:
      - get-values
      - lint
      - check-skip-duplicate
      - pulumi-workflow
    permissions:
      statuses: write # needed for updating status on PRs
    if: always()
    steps:
      # - name: Set status for duplicate detection
      #   if: needs.check-skip-duplicate.outputs.should-run != 'true'
      #   env:
      #     GH_TOKEN: ${{ github.token }}
      #   run: |
      #     gh api \
      #       -X POST -H "Accept: application/vnd.github.v3+json" \
      #       "/repos/${{ github.repository }}/statuses/${{ github.sha }}" \
      #       -f state=pending -f context="required-check" -f description="⏭️ Workflow skipped due to duplicate detection"
      #     echo "⏭️ Workflow was skipped due to duplicate detection - status set to pending to block merge"
      #     exit 0

      - name: fail if prior job failure
        run: |
          failure_pattern="^(failure|cancelled)$"

          if [[ "${{ needs.check-skip-duplicate.result }}" =~ $failure_pattern ]] ||
             [[ "${{ needs.lint.result }}" =~ $failure_pattern ]] ||
             [[ "${{ needs.pulumi-workflow.result }}" =~ $failure_pattern ]] ||
             [[ "${{ needs.get-values.result }}" =~ $failure_pattern ]]; then
            echo "❌ One or more jobs failed or were cancelled"
            exit 1
          fi
          echo "✅ All jobs completed successfully or were skipped"

      - name: Mark the required-check from the job triggered by the push as succeeded so the PR can be merged
        if: ${{ github.event_name == 'pull_request' && needs.check-skip-duplicate.outputs.should-run == 'true'}}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
            -X POST -H "Accept: application/vnd.github.v3+json" \
            "${{ github.event.pull_request.statuses_url }}" \
            -f state=success -f context="required-check" -f description="✅ All required checks passed in the job triggered by pull_request" \
            -f target_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Mark updated Dependabot commit of devcontainer hash as succeeded
        if: needs.get-values.outputs.dependabot-commit-created == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
            -X POST -H "Accept: application/vnd.github.v3+json" \
            "/repos/${{ github.repository }}/statuses/${{ needs.get-values.outputs.new-dependabot-sha }}" \
            -f state=success -f context="required-check" -f description="Initial CI run passed" \
            -f target_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
