name: CI

on:
  push:
    branches-ignore:
      - 'gh-readonly-queue/**' # don't run (again) when on these special branches created during merge groups; the `on: merge_group` already triggers it.
  merge_group:

env:
  PYTHONUNBUFFERED: True
  PRE_COMMIT_HOME: ${{ github.workspace }}/.precommit_cache

permissions:
    id-token: write
    contents: write # needed for mutex, and updating dependabot branches
    statuses: write # needed for updating status on Dependabot PRs

jobs:
  get-values:
    uses: ./.github/workflows/get-values.yaml

  lint:
    needs: [ get-values ]
    name: Pre-commit
    uses: ./.github/workflows/pre-commit.yaml
    with:
      python-version: 3.12.7

  pulumi-workflow:
    uses: ./.github/workflows/pulumi-aws.yml
    needs: [ lint ]
    with:
      AWS_REGION: us-east-1
      PULUMI_STACK_NAME: prod
      PYTHON_VERSION: 3.12.7
      DEPLOY_SCRIPT_MODULE_NAME: aws_organization.lib
      PULUMI_PREVIEW: true
      PREVIEW_ROLE_NAME: OrgRootInfraPreview
      PULUMI_UP: ${{ github.ref == 'refs/heads/main' }}
      PULUMI_UP_ROLE_NAME: OrgRootInfraDeploy
      AWS_ACCOUNT_ID: "789893201852"

  required-check:
    runs-on: ubuntu-24.04
    needs:
      - get-values
      - pulumi-workflow
    if: always()
    steps:
      - name: fail if prior job failure
        if: needs.get-values.result != 'success' || needs.pulumi-workflow.result != 'success'
        run: |
          exit 1
      - name: Mark updated Dependabot commit of devcontainer hash as succeeded
        if: needs.get-values.outputs.dependabot-commit-created == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
            -X POST -H "Accept: application/vnd.github.v3+json" \
            "/repos/${{ github.repository }}/statuses/${{ needs.get-values.outputs.new-dependabot-sha }}" \
            -f state=success -f context="required-check" -f description="Initial CI run passed" \
            -f target_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
