name: Refresh Stack

on:
  workflow_dispatch:

env:
  PYTHONUNBUFFERED: True
  PRE_COMMIT_HOME: ${{ github.workspace }}/.precommit_cache

permissions:
    id-token: write
    contents: write # needed for mutex

jobs:
  lint:
    name: Pre-commit
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install latest versions of python packages
        uses: ./.github/actions/install_deps
        with:
          python-version: 3.12.7

      - name: Set up mutex # Github concurrency management is horrible, things get arbitrarily cancelled if queued up. So using mutex until github fixes itself. When multiple jobs are modifying cache at once, weird things can happen.  possible issue is https://github.com/actions/toolkit/issues/658
        if: ${{ runner.os != 'Windows' }} # we're just gonna have to YOLO on Windows, because this action doesn't support it yet https://github.com/ben-z/gh-action-mutex/issues/14
        uses: ben-z/gh-action-mutex@1ebad517141198e08d47cf72f3c0975316620a65 # v1.0.0-alpha.10
        with:
          branch: mutex-venv-ubuntu-24.04-py3.12.7
        timeout-minutes: 30 # this is the amount of time this action will wait to attempt to acquire the mutex lock before failing, e.g. if other jobs are queued up in front of it

      - name: Cache Pre-commit hooks
        uses: actions/cache@v4.2.3
        env:
          cache-name: cache-pre-commit-hooks
        with:
          path: ${{ env.PRE_COMMIT_HOME }}
          key: ubuntu-24.04-py3.12.7-build-${{ env.cache-name }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ubuntu-24.04-py3.12.7-build-${{ env.cache-name }}-

      - name: Run pre-commit
        run:  pre-commit run -a

  pulumi-refresh:
    uses: ./.github/workflows/pulumi-aws.yml
    needs: [ lint ]
    with:
      AWS_REGION: us-east-1
      PULUMI_STACK_NAME: prod
      PYTHON_VERSION: 3.12.7
      DEPLOY_SCRIPT_MODULE_NAME: aws_organization.lib
      PULUMI_PREVIEW: true
      PREVIEW_ROLE_NAME: OrgRootInfraPreview
      PULUMI_REFRESH: true
      REFRESH_ROLE_NAME: OrgRootInfraDeploy
      AWS_ACCOUNT_ID: "789893201852"

  pulumi-preview-after-refresh:
    uses: ./.github/workflows/pulumi-aws.yml
    needs: [ pulumi-refresh ]
    with:
      AWS_REGION: us-east-1
      PULUMI_STACK_NAME: prod
      PYTHON_VERSION: 3.12.7
      DEPLOY_SCRIPT_MODULE_NAME: aws_organization.lib
      PULUMI_PREVIEW: true
      PREVIEW_ROLE_NAME: OrgRootInfraPreview
      AWS_ACCOUNT_ID: "789893201852"
