name: Refresh Stack

on:
  workflow_dispatch:

env:
  PYTHONUNBUFFERED: True
  PRE_COMMIT_HOME: ${{ github.workspace }}/.precommit_cache

permissions:
    id-token: write # needed to assume OIDC roles (e.g. for downloading from CodeArtifact)

jobs:
  lint:
    name: Pre-commit
    uses: ./.github/workflows/pre-commit.yaml
    permissions:
      contents: write # needed for mutex
      id-token: write # needed to assume OIDC roles (e.g. for downloading from CodeArtifact)
    with:
      python-version: 3.12.7

  pulumi-refresh:
    uses: ./.github/workflows/pulumi-aws.yml
    needs: [ lint ]
    permissions:
      id-token: write # needed to assume OIDC roles (e.g. for downloading from CodeArtifact)
      contents: write # needed for mutex
    with:
      AWS_REGION: us-east-1
      PULUMI_STACK_NAME: prod
      PYTHON_VERSION: 3.12.7
      DEPLOY_SCRIPT_MODULE_NAME: aws_organization.lib
      PULUMI_PREVIEW: true
      PREVIEW_ROLE_NAME: OrgRootInfraPreview
      PULUMI_REFRESH: true
      REFRESH_ROLE_NAME: OrgRootInfraDeploy
      AWS_ACCOUNT_ID: "789893201852"

  pulumi-preview-after-refresh:
    uses: ./.github/workflows/pulumi-aws.yml
    needs: [ pulumi-refresh ]
    permissions:
      id-token: write # needed to assume OIDC roles (e.g. for downloading from CodeArtifact)
      contents: write # needed for mutex
    with:
      AWS_REGION: us-east-1
      PULUMI_STACK_NAME: prod
      PYTHON_VERSION: 3.12.7
      DEPLOY_SCRIPT_MODULE_NAME: aws_organization.lib
      PULUMI_PREVIEW: true
      PREVIEW_ROLE_NAME: OrgRootInfraPreview
      AWS_ACCOUNT_ID: "789893201852"
